cyberchaser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('dashboard/', include('dashboard.urls')),
]

dashboard/urls.py
from django.urls import path
from . import views # import the views of current app


app_name = 'dashboard'
urlpatterns = [
	path("", views.index, name="index"), # attach index view to "index" url
	path("domains/", views.domains, name="domains"),
	path("scope/", views.scope, name="scope"),
	path("gitdorks/", views.githubdorks, name='gitdorks'),
	path("ggdorks/", views.googledorks, name='ggdorks'),
	path("acquisitions/", views.acquisitions, name='acquisitions'),
	path("methodology/", views.methodology, name='methodology'),
	path("mynotes/", views.myNotes, name='myNotes'),
	path("profile/", views.profile, name='profile'),
	path("logout/", views.logout_user, name='logout'),
]

login/urls.py
from django.urls import path
from . import views # import the views of current app


app_name = 'login'
urlpatterns = [
	path("", views.index, name="index"),
]

dashboard/models.py
from django.db import models
import datetime

class Program(models.Model):
    def __str__(self):
        return self.ProgramName
    ProgramName = models.CharField(max_length=30, default="program name")
    domain = models.CharField(max_length=30, default="domain name")
    domains = models.TextField(default="Domains Related")
    acquisitions = models.TextField(default="Companies Accuired.")
    start_date = datetime.date.today()

class Githubdorks(models.Model):
    def __str__(self):
        return self.DorkName
    DorkName = models.CharField(max_length=30, default="Dork Name")

class Googledorks(models.Model):
    def __str__(self):
        return self.dork_name
    dork_name = models.CharField(max_length=30, default="Dork Name")
    dork_desc = models.CharField(max_length=40, default="Dork description")

class MyNotes(models.Model):
    def __str__(self):
        return self.note_name
    note_name    = models.CharField(max_length=30, default="Note Name")
    note_content = models.TextField(default="Note description")
    note_date = datetime.date.today()

class Methodology(models.Model):
    methodology_content = models.TextField(default="No Methodology Yet !")

class Scope(models.Model):
    def __str__(self):
        return self.program_name
    program_name = models.CharField(max_length=20, default="Program Name")
    in_scope = models.TextField(default="in scope")
    out_scope = models.TextField(default="out scope")

dashboard/views.py
from django.shortcuts import render, redirect
from .models import Googledorks, Program, Githubdorks, MyNotes, Methodology, Scope
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .core.acquisitions import Acquisitions
from .core.dns import PortScanning
from .core.domains import Domains

# global variables
acq = ''
domain = ''
get_domain = ''
domains = []
subs_db = []
save__option = ''
old_program = ''
org_name = ''
programs = Program.objects.all().order_by('-id')
github_dorks = Githubdorks.objects.all().order_by('-id')
google_dorks = Googledorks.objects.all().order_by('-id')


def check_save(domain_name, field_name, field_value):
    if field_name == "acquisitions":
        if not Program.objects.filter(domain=domain_name).exists():
            Program(ProgramName=program__name, domain=domain_name, acquisitions=field_value).save()
            Message = f"{program__name} Was Added Successfully."
        else:
            Program.objects.filter(domain=domain_name).update(acquisitions=field_value)
            Message = f"{program__name} Has Updated."
    elif field_name == "domains":
        if not Program.objects.filter(domain=domain_name).exists():
            Program(ProgramName=program__name, domain=domain_name, domains=field_value).save()
            Message = f"{program__name} Was Added Successfully."
        else:
            Program.objects.filter(domain=domain_name).update(domains=field_value)
            Message = f"{program__name} Has Updated."
    else:
        Message = ''
    return Message

@login_required
def index(request):
    global domain, acq, domains, Ipv4, programs, program__name, latest_program, get_domain, org_name
    ip_scan_results = ''
    delete_notification = ''
    if request.method == 'POST':
        Message = ''
        domain = request.POST.get('domain')
        program__name = domain.split('.')[0]
        scan_types = request.POST.getlist("scan_types")
        old_program = request.POST.get('old_program')
        save__option = request.POST.get('save__check')
        if len(scan_types) != 0:
            for type in scan_types:
                if type == 'domains':
                    domains, org_name = Domains(domain).get_domains()
                    if save__option == 'save':
                        Message = check_save(domain, "domains", domains)
                elif type == "acq":
                    acq = Acquisitions(domain).result()
                    if save__option == 'save':
                        Message = check_save(domain, "acquisitions", acq)
                elif type == 'git_dork':
                    get_domain = domain
                programs = Program.objects.all().order_by('-id')
            return render(request, 'dashboard/index.html', {'gitdorks': github_dorks, "ggdorks": google_dorks, "acq" : acq, 'domains': domains, 'programs': programs, 'message': Message})
        else:
            get_program = Program.objects.get(id = old_program)
            domain = get_program.ProgramName
            acq = eval(get_program.acquisitions)
            domains  = eval(get_program.domains)
            context = {
                'gitdorks': github_dorks,
                "ggdorks": google_dorks,
                'programs': programs,
                'one_program': get_program,
                'acq': acq.items,
                'domains': domains
            }
            return render(request, "dashboard/index.html", context)

    if request.GET.get('delete'):
        program_id = request.GET.get('delete')
        program_selected = Program.objects.get(id = program_id)
        program_selected_id = program_selected.id
        program_selected_name = program_selected.ProgramName
        Program.objects.get(id=program_selected_id).delete()
        delete_notification = f"{program_selected_name} Deleted Successfully !"
        programs = Program.objects.all()  # update programs table

    if request.GET.get('port_scan'):
        ip = request.GET.get('port_scan')
        ip_scan_results = PortScanning(ip).ScanIP()
    context = {
        'gitdorks': github_dorks,
        "ggdorks": google_dorks,
        "acq" : acq,
        'domains': domains,
        'programs': programs,
        "delete_notification": delete_notification,
        "ip_scan": ip_scan_results
    }
    return render(request, "dashboard/index.html", context)

@login_required
def domains(request):
    global subdomains, domain, domains, org_name
    programs = Program.objects.all()
    if request.method == "POST":
        old_program = Program.objects.get(id=request.POST.get('old__program'))
        domain = old_program.ProgramName
        domains = eval(old_program.domains)
    context = {
        'domain': domain,
        'domains': domains,
        'programs': programs,
        "org_name": org_name
    }
    return render(request, "dashboard/domains.html", context)


@login_required
def scope(request):
    scope_programs = Scope.objects.all()
    if request.GET.get("delete_scope"):
        delete_scope = request.GET.get("delete_scope")
        program_name = Scope.objects.filter(id=delete_scope).get()
        Scope.objects.filter(id=delete_scope).delete()
        Message = f"{program_name.program_name} Scope Deleted !"
        scope_programs = Scope.objects.all()
        return render(request, 'dashboard/my-notes.html', {"scope_programs": scope_programs, "Message": Message})
    if request.method == "POST":
        program_name = request.POST.get('program_name')
        in_scope = request.POST.get('in_scope')
        out_scope = request.POST.get('out_scope')
        Scope(program_name=program_name, in_scope=in_scope, out_scope=out_scope).save()
        messages.success(request, f"{program_name} Scope Added !")
        scope_programs = Scope.objects.all()
    return render(request, "dashboard/scope.html", {"scope_programs": scope_programs})


@login_required
def githubdorks(request):
    get_domain = ''
    github_dorks = Githubdorks.objects.all().order_by('-id')
    if request.method == 'POST':
        if request.POST.get('domain_name'):
            context = {
                "all_dorks": github_dorks,
                "domain": request.POST.get("domain_name")

            }
            return render(request, "dashboard/github-dorks.html", context)
        else:
            dork_name = request.POST.get('dork_name')
            Githubdorks(DorkName=dork_name).save()
            messageSuccess = f"{dork_name} Dork Saved To Database."
            github_dorks = Githubdorks.objects.all().order_by('-id')
            return render(request, "dashboard/github-dorks.html", {'all_dorks': github_dorks, 'domain': get_domain, 'success': messageSuccess})
    return render(request, "dashboard/github-dorks.html")

@login_required
def googledorks(request):
    google_dorks = Googledorks.objects.all().order_by('-id')
    if request.method == "POST":
        if request.POST.get('domain'):
            context = {
                "all_dorks": google_dorks,
                "domain": request.POST.get('domain')
            }
            return render(request, "dashboard/google-dorks.html", context)
        else:
           dork_name = request.POST.get('dork_name')
           dork_desc = request.POST.get('dork_desc')
           Googledorks(dork_name=dork_name, dork_desc=dork_desc).save()
           messageSuccess = f"{dork_name} Dork Saved To Database."
           return render(request, "dashboard/google-dorks.html", {'all_dorks': google_dorks, 'domain': get_domain, 'success': messageSuccess})
    return render(request, "dashboard/google-dorks.html")

@login_required
def acquisitions(request):
    global domain, acq
    if request.method == "POST":
        old_program = Program.objects.get(id=request.POST.get('old__program'))
        domain = old_program.ProgramName
        if not old_program.acquisitions:
            return render(request, 'dashboard/acquisitions.html', {'programs': programs})
        acq = eval(old_program.acquisitions)
        return render(request, 'dashboard/acquisitions.html', {'result': acq.items, 'domain': domain, 'programs': programs})
    if acq: 
        return render(request, 'dashboard/acquisitions.html', {'result': acq.items, 'domain': domain, 'programs': programs})
    return render(request, 'dashboard/acquisitions.html', {'programs': programs})

@login_required
def myNotes(request):
    my_notes = MyNotes.objects.all()
    if request.GET.get("note_id"):
        note_id = request.GET.get("note_id")
        single_note = MyNotes.objects.get(id=note_id)
        context = {
            "all_notes": my_notes,
            "note": single_note
        }
        return render(request, 'dashboard/my-notes.html', context)
    if request.GET.get('delete_note'):
        note_id = request.GET.get('delete_note')
        MyNotes.objects.get(id=note_id).delete()
        my_notes = MyNotes.objects.all()
        context = {
            "all_notes": my_notes,
            "message": "Note Has Been Deleted."
        }
        return render(request, 'dashboard/my-notes.html', context)
    if request.method == "POST":
        noteName = request.POST.get('noteName')
        noteContent = request.POST.get('noteContent')
        MyNotes(note_name=noteName, note_content=noteContent).save()
        my_notes = MyNotes.objects.all()
        context = {
            "all_notes": my_notes,
            "message": "Note Was Added Successfully"
        }
        return render(request, 'dashboard/my-notes.html', context)
    context = {
        "all_notes": my_notes
    }
    return render(request, 'dashboard/my-notes.html', context)

@login_required
def methodology(request):
    if Methodology.objects.count() == 0:
        Methodology(methodology_content="Nothing Yet").save()
        my_methodology = Methodology.objects.all().first()
        record_id = my_methodology.id
    else:

templates/dashboard/acquisitions.html
{% extends 'dashboard/base.html' %}
{% block body %}
        <div class="content">
            <div class="navigationBar">
                <button id="sidebarToggle" class="btn sidebarToggle">
                <i class="fa fa-arrow-left togglebtn"></i>
            </div>
            <div class="container-fluid home__dashboard">
                <div class="container-fluid intro__home">
                    <div class="row">
                        <div class="col-md-12">
                            <h3 class="text-muted text-center text-uppercase"> 
                                {% if domain %}
                                All Acquisitions Of {{domain}}
                                {% else %}
                                No Program Selected Yet
                                {% endif %}
                            </h3>
                        </div>
                    </div>
                </div>
                <!-- Table Content Subdomains -->
                <div class="container">
                    <div class="card home__tables">
                        <div class="card-header table__header__custom">
                            <div class="container-fluid">
                                <div class="d-flex align-items-center justify-content-end">
                                    <form action="#" method='POST' class="form-group">
                                        {% csrf_token %}
                                        <select class="form-select custom__target_select" aria-label="Default select example" onchange="this.form.submit();" name="old__program">
                                            <option default>All Programs</option>
                                            {% if programs %}
                                                {% for program in programs %}
                                                    <option value="{{program.id}}">
                                                        {{program.ProgramName}}
                                                    </option>
                                                {% endfor %}
                                            {% endif %}
                                        </select> 
                                    </form>  
                                </div>
                            </div>
                        </div>
                        <div class="card-body card__body_custom">
                            <table class="table text-center">
                                <tr>
                                    <th>#</th>
                                    <th>Company Name</th>
                                    <th>Acquired on</th>
                                </tr>
                                {% for acq, date in result %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>{{acq}}</td>
                                    <td>20{{date}}</td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock body %}

templates/dashboard/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <title>CyberChaser | Bug Bounty Recon Framework</title>
    <link rel="shortcut icon" href="{% static 'dashboard/images/cc_logo.ico' %}" type="image/x-icon">
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Monoton&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'dashboard/assets/index.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/assets/style.css' %}">
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.all.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/33.0.0/classic/ckeditor.js"></script>
    <script src="{% static 'dashboard/assets/index.js' %}"></script>
    <script src="{% static 'dashboard/assets/notification.js' %}"></script>

    </head>


    <body>
        
    <div class="page">

        <div class="sidebar">
            <div class="sidebar-header">
                <div class="sidebar-logo-container">
                    <div class="logo-container">
                        <!--
                            Enable Once You Have Logo
                        <img class="logo-sidebar" src="https://via.placeholder.com/400" />
                        -->
                        <h1>C<sub>C</sub></h1>
                    </div>
                    <div class="brand-name-container">
                        <p class="brand-name">
                            CyberChaser<br />
                            <span class="brand-subname">
                            By SC
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            <div class="sidebar-body">
                <ul class="navigation-list">
                    <li class="navigation-list-item" id='dashboard'>
                        <a class="navigation-link" href="{% url 'dashboard:index' %}">
                            <div class="row">
                                <div class="col-2">
                                    <i class="fas fa-tachometer-alt"></i>
                                </div>
                                <div class="col-9">
                                    Dashboard
                                </div>
                            </div>
                        </a>
                    </li>

                    {% comment %} Domains Functionality {% endcomment %}
                    <li class="navigation-list-item" id='domains'>
                        <a class="navigation-link" href="{% url 'dashboard:domains' %}">
                            <div class="row">
                                <div class="col-2">
                                    <i class="fas fa-align-left"></i>
                                </div>
                                <div class="col-9">
                                    Domains
                                </div>
                            </div>
                        </a>
                    </li>

                    <li class="navigation-list-item" id='scope'>
                        <a class="navigation-link" href="{% url 'dashboard:scope' %}">
                            <div class="row">
                                <div class="col-2">
                                    <i class="fas fa-crosshairs"></i>
                                </div>
                                <div class="col-9">
                                    Scope
                                </div>
                            </div>
                        </a>
                    </li>

                    <li class="navigation-list-item" id='gitdorks'>
                        <a class="navigation-link" href="{% url 'dashboard:gitdorks' %}">
                            <div class="row">
                                <div class="col-2">
                                    <i class="fas fa-code"></i>
                                </div>
                                <div class="col-9">
                                    Github Dorks
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="navigation-list-item" id='ggdorks'>
                        <a class="navigation-link" href="{% url 'dashboard:ggdorks' %}">
                            <div class="row">
                                <div class="col-2">
                                    <i class="fas fa-search"></i>
                                </div>
                                <div class="col-9">
                                    Google Dorks
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="navigation-list-item" id='acq'>
                        <a class="navigation-link" href="{% url 'dashboard:acquisitions' %}">
                            <div class="row">
                                <div class="col-2">
                                    <i class="fas fa-location-arrow"></i>
                                </div>
                                <div class="col-9">
                                    Acquisitions
                                </div>
                            </div>
                        </a>
                    </li>

                    <hr style="color:#fff;margin-top:30px;">

                    <li class="navigation-list-item" id='notes'>
                        <a class="navigation-link" href="{% url 'dashboard:myNotes' %}">
                            <div class="row">
                                <div class="col-2">
                                    <i class="fas fa-sticky-note"></i>
                                </div>
                                <div class="col-9">
                                    My Notes
                                </div>
                            </div>
                        </a>
                    </li>
                    <li class="navigation-list-item" id='mtd'>
                        <a class="navigation-link" href="{% url 'dashboard:methodology' %}">
                            <div class="row">
                                <div class="col-2">
                                    <i class="fas fa-clipboard-check"></i>
                                </div>
                                <div class="col-9">
                                    Methodology
                                </div>
                            </div>
                        </a>
                    </li>

                    <li class="navigation-list-item" id="profile">
                        <a class="navigation-link" href="{% url 'dashboard:profile' %}">
                            <div class="row">
                                <div class="col-2">
                                    <i class="fas fa-cog"></i>
                                </div>
                                <div class="col-9">
                                    Profile
                                </div>
                            </div>
                        </a>
                    </li>
        
                </ul>
        
                <ul class="navigation-list" style="position: absolute; bottom: 0; width: 100%;">

                    <li class="navigation-list-item active">
                        <a class="navigation-link" href="{% url 'dashboard:logout' %}">
                            <div class="row">
                                <div class="col-2">
                                    <i class="fas fa-sign-out-alt"></i>
                                </div>
                                <div class="col-9">
                                    Logout
                                </div>
                            </div>
                        </a>
                    </li>
            </div>
        </div>
{% block body %}
{% endblock body %}    
    </div>
<script src="{% static 'dashboard/assets/app.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js">
</script>
<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        });
</script>

</body>


</html>

templates/dashboard/domains.html
{% extends 'dashboard/base.html' %}

{% block body %}
        <div class="content">
            <div class="navigationBar">
                <button id="sidebarToggle" class="btn sidebarToggle">
                    <i class="fa fa-arrow-left togglebtn"></i>
            </div>
            <div class="container-fluid home__dashboard">
                {% comment %} <div class="container-fluid intro__home">
                    <div class="row">
                        <div class="col-md-12">
                            <h3 class="text-muted text-center text-uppercase">
                                {% if domain %}
                                All Domains Of {{domain}}
                                {% else %}
                                No Program Selected Yet
                                {% endif %}
                            </h3>
                        </div>
                    </div>
                </div> {% endcomment %}
                <!-- Table Content Domains -->
                <div class="container">
                    <div class="card home__tables home__tables__without__title">
                        <div class="card-header table__header__custom">
                            <div class="container-fluid">
                                <div class="d-flex align-items-center justify-content-between">
                                    <h5 class="methodology_intro">
                                        <i class="fas fa-align-left"></i>
                                        {% if domain %}
                                        All Domains Of {{domain}}
                                        {% else %}
                                        No Program Selected Yet
                                        {% endif %}
                                    </h5>
                                    <form action="#" method='POST' class="form-group">
                                        {% csrf_token %}
                                        <select class="form-select custom__target_select" aria-label="Default select example" onchange="this.form.submit();" name="old__program">
                                            <option default>All Programs</option>
                                            {% if programs %}
                                                {% for program in programs %}
                                                    <option value="{{program.id}}">
                                                        {{program.ProgramName}}
                                                    </option>
                                                {% endfor %}
                                            {% endif %}
                                        </select>  
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="card-body card__body_custom">
                            <table class="table text-center text-white">
                                <tr>
                                    <th>#</th>
                                    <th>Domains</th>
                                    <th>Matching Identities</th>
                                </tr>
                                {% if domains %}
                                    {% for domain in domains %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>
                                        <a href="https://{{domain}}" target='_blank'
                                            class="btn btn-link text-decoration-none text-white">
                                            {{domain}}
                                        </a>
                                    </td>
                                    <td>
                                        {% if org_name %}
                                            {{org_name}}
                                        {% else %}
                                        <a href="#" class="btn custom__btn btn-sm">
                                            {% comment %} <i class="far fa-trash-alt"></i> {% endcomment %}
                                            Not Found
                                        </a>
                                        {% endif %}
                                    </td>
                                </tr>
                                    {% endfor %}
                                {% endif %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock body %}